### ISSUE TITLE
CardElement on* events aren't firing

### ISSUE THREAD

**Issue by mr-tech** [wobsoriano/solid-stripe#19]
I'm attempting to use the CardElement and none of the on* events (`onBlur`, `onFocus`, `onChange`, etc.) seem to be properly connected. Though everything seems fine with submission when calling `createPaymentMethod()`.

I'm porting over React code and was using the `onChange` event to handle errors from Stripe in real-time, but that doesn't seem possible atm.

Versions
```json
"@stripe/stripe-js": "^4.9.0",
"solid-js": "^1.9.3",
"solid-stripe": "^0.7.0"
```

Extremely basic repro

```ts
import { createSignal, onMount } from 'solid-js';
import { loadStripe } from '@stripe/stripe-js';
import { CardElement, Elements } from 'solid-stripe';

import type { Stripe } from '@stripe/stripe-js';

const STRIPE_KEY = '';

const App = () => {
  const [stripe, setStripe] = createSignal<null | Stripe>(null);

  onMount(() => { void loadStripe(STRIPE_KEY).then(setStripe); });

  return (
    <div style={{
      'background-color': '#282c34',
      'min-height': '100vh',
      display: 'flex',
      'flex-direction': 'column',
      'align-items': 'center',
      'justify-content': 'center',
      color: 'white',
    }}
    >
      <div
        style={{
          width: '640px',
          padding: '20px',
          'background-color': 'white',
        }}
      >
        <Elements stripe={stripe()}>
          <CardElement
            onBlur={() => console.log('onBlur')}
            onFocus={() => console.log('onFocus')}
            onEscape={() => console.log('onEscape')}
            onLoadError={(event) => console.log('onLoadError', event)}
            onNetworksChange={(event) => console.log('onNetworksChange', event)}
            onReady={() => console.log('onReady')}
            onChange={(event) => console.log('onChange', event)}
          />
        </Elements>
      </div>
    </div>
  );
};

export default App;
```

What I expect is that the events fire when expected: `onFocus` when focus is granted, `onBlur` when focus is lost, etc. Most importantly, `onChange` when the Card Element detects a change in state (error, completion, etc.)

What I am experiencing is that no events are firing. Though submission is still possible, the app is unable to see the state of the Card Element and so is unable to do things like disable / re-enable buttons when there's a change in errors or completion.

**Comment by wobsoriano** [comment]
I think the issue here is that I'm invoking the accessors [here](https://github.com/wobsoriano/solid-stripe/blob/1aac234d7ac42e7a37b3f003e4de271ca981e84b/src/components/createElementComponent.tsx#L60,L71) and the [custom primitive](https://github.com/wobsoriano/solid-stripe/blob/1aac234d7ac42e7a37b3f003e4de271ca981e84b/src/components/createElementComponent.tsx#L96) never reacts to it.

Opened a PR that should fix this

**Comment by mr-tech** [comment]
Most of the events are firing now (I'm seeing `onBlur`, `onFocus`, `onEscape`, and `onReady`), however `onChange` is still not firing.

Also, the component is throwing an error when mounting:
`Uncaught (in promise) IntegrationError: When adding an event listener, the second argument should be a function callback.`

Upon doing some digging, it looks like any `undefined` handlers cause this error and any `useAttachEvent` calls after the error fail to bind. (Or maybe they bind but are immediately unbound because of the error? Either way, they're not attached by the time the form is interactable.)

Changing line https://github.com/wobsoriano/solid-stripe/blob/0119f06c847a0f71aedb5549d83748ecb99acd6c/src/components/createElementComponent.tsx#L102 to 
```ts
if (!element() || !cb) {
```
seems to do the trick.

**Comment by mr-tech** [comment]
As an aside, `options` doesn't appear to be reactive. There's a `disabled` prop in there used to disable the form input. If this would be better off as a separate issue, lmk.

**Comment by wobsoriano** [comment]
Awesome, thanks for this. I'll release a quick patch for the event listener callback issue. Will do a separate one for the options. Will investigate

**Comment by mr-tech** [comment]
> Awesome, thanks for this. I'll release a quick patch for the event listener callback issue. Will do a separate one for the options. Will investigate

Decided to see if I couldn't sus it out. Seems like a `createEffect` with a call to `element().update()` is what we're looking for. Example:
```ts
createEffect(() => {
  if (element()) {
    element()!.update(props.options as any)
  }
});
```

**Comment by wobsoriano** [comment]
Yup that's we're looking for. I'll make sure we only update it when needed

**Comment by wobsoriano** [comment]
@mr-tech should be available in the latest release

**Comment by mr-tech** [comment]
> @mr-tech should be available in the latest release

Hey. Thanks for the quick responses! I just got around to checking out the releases. Seems as though there's a slight oversight in the callback check.

https://github.com/wobsoriano/solid-stripe/blob/040419061ae4f1f2e319a9942e25506d11f74b54/src/components/createElementComponent.tsx#L118

This should be `||` not `&&`.

**Comment by wobsoriano** [comment]
You want to do a quick PR for that @mr-tech ? 😄
